### ISSUE TITLE
Apostrophe breaks MyBB Editor field. See Gyazo video.

### ISSUE THREAD

**Issue by BouncingHitman** [burnacid/MyBB-Form-Creator#114] opened 2019-07-03 03:29 UTC
**Describe the bug**
When using the MyBB editor field, putting an apostrophe ( ' ) corrupts the form.

**To Reproduce**
https://gyazo.com/ba1661acf0dc2028e1e9f28a5113782f

**Expected behavior**
Forms are un-submitable unless the apostrophe is removed from the paragraph.
It was brought to our attention by our staff.

**Desktop (please complete the following information):**
 - MyBB version:1.8.21
 - Plugin version: (2.6.2)
 - PHP version: 7.2.19-0ubuntu0.18.04.1
 - MySQL version: latest?

**Additional context**

**Comment by burnacid** [comment] 2019-07-03 04:06
Thanks for you issue. I'll look into it as soon as possible

**Comment by BouncingHitman** [comment] 2019-07-03 07:34
> Thanks for you issue. I'll look into it as soon as possible

Sweet! Let me know if there's any temporary fixes I can make until an official update is pushed

**Comment by burnacid** [comment] 2019-07-03 14:29
I have tried to reproduce it. Can you send me and export of your form please.

**Comment by BouncingHitman** [comment] 2019-07-04 00:40
> I have tried to reproduce it. Can you send me and export of your form please.

I was doing some testing and made a new form from scratch. A basic form with the mybb editor and submit button seems to work fine. However, on my other forms it's a different story. Here's the export code (Process and Permissions turned ON, Usage log turned OFF):
`[{"name":"Ban Form","active":"1","fid":"4","tid":"8","overridebutton":"1","class":"","settings":{"allowedgidtype":"0","allowedgid":["4","10","11","13","14","15"],"customdenied":"You must be an administrator or higher to access this function.\r\nAre you looking to create a <a href=\"\/form.php?formid=3\">new ban request<\/a>?","limitusage":"0","pmusers":"","prefix":"0","uid":"","customsuccess":"\/forumdisplay.php?fid=4","signature":"0","posticon":"0","showsummary":"1","summaryparsed":"0","customsummary":"Please review that all the information provided is correct.","width":"25","labelwidth":"25","pmgroups":[""]},"subjecttemplate":"Case $fieldvalue[3]","messagetemplate":"","fields":[{"fieldid":"1","name":"Administrator's name","description":"The administrator taking care of the ban","type":"1","default":"","required":"1","order":"0","class":"","settings":{"placeholder":"Administrator's name","maxlength":"0","regex":"","regexerror":"","size":"20"}},{"fieldid":"2","name":"Player's name","description":"The player's in-game name at the time of the incident","type":"1","default":"","required":"1","order":"1","class":"","settings":{"placeholder":"Player's name","maxlength":"0","regex":"","regexerror":"","size":"20"}},{"fieldid":"3","name":"Case number","description":"View the <a href=\"\/forum-4.html\">ban storage<\/a> for the next case number.","type":"1","default":"#","required":"1","order":"2","class":"","settings":{"placeholder":"Case number","maxlength":"4","regex":"","regexerror":"","size":"20"}},{"fieldid":"5","name":"SteamID, GUID and\/or IP","description":"<u>GUID is required<\/u>","type":"2","default":"","required":"1","order":"4","class":"","settings":{"placeholder":"cb856a24fca7caabb9a389c458b6562f, 70.69.151.4","maxlength":"","regex":"","regexerror":"","cols":"35","rows":"3","resize":"1"}},{"fieldid":"6","name":"Reason for the ban","description":"Something short, please","type":"1","default":"","required":"1","order":"5","class":"","settings":{"placeholder":"Ban reason","maxlength":"0","regex":"","regexerror":"","size":"35"}},{"fieldid":"7","name":"Ban length","description":"How long is this player being banned for?","type":"1","default":"","required":"1","order":"6","class":"","settings":{"placeholder":"Time","maxlength":"0","regex":"","regexerror":"","size":"20"}},{"fieldid":"10","name":"Query notes","description":"Additional information pertinent to the case","type":"15","default":"","required":"1","order":"7","class":"","settings":{"rows":""}},{"fieldid":"8","name":"Submit","description":"","type":"11","default":"","required":"0","order":"8","class":"","settings":null}]}]`

**Comment by burnacid** [comment] 2019-07-04 16:23
So the issue is probably because of the summary page. The saved data is broken by the Apostrophe. For now disabling the summary field is a way to quick fix it.

I'll push a fix as soon as possible

**Comment by burnacid** [comment] 2019-07-04 17:11
Or download the development branch. It contains the possible fix.
It will be a few days before I push it torwards MyBB Extend

**Comment by BouncingHitman** [comment] 2019-07-04 23:29
Thank you for your time burnacid. Brilliant work on these forms. I'll have you know that we've got over 30 active staff members using those forms to file cases on players that we ban from our game server. It's also used for various other things. I really like how you can pull the field values and put them in the subject. Well done.

I updated the file on our server using the one you updated 6 hours ago, and so far so good. We'll let you know if we bump into some other obstacles. Thanks.

**Comment by burnacid** [comment] 2019-07-05 03:39
Thanks, that is exactly what I use it for and why I developed it. After years of making custom forms manually to do this. I'm closing the issue.

**Closed by burnacid** 2019-07-05 03:39 UTC
Labels: Confirmed, bug
